apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-rol
  labels:
   "kubernetes.io/name": 'jenkins'
rules:
- apiGroups: [""]
  resources: ["namespaces","pods","services"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: ["apps","extensions"]
  resources: ["deployments","replicasets"]
  verbs: ["create","delete","get","list","patch","update","watch"]  
- apiGroups: [""]
  resources: ["persistentvolume","persistentvolume"]
  verbs: ["get","list"]    
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer-rol
subjects:
- kind: ServiceAccount
  name: jenkins-deployer-sa
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: jenkins-deployer-token
  annotations:
    kubernetes.io/service-account.name: "jenkins-deployer-sa"