apiVersion: v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
  serviceAccountName: jenkins      
    spec:
      containers:
        - name: hello-app
          image: dionicio1/hello-app
          ports:
            - containerPort: 8080  
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
spec:
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  serviceAccountName: jenkins